INSERT INTO public.about_us_configs (id,header_badge,header_title,header_description,primary_button_text,secondary_button_text,differentials,achievements,created_at,updated_at) VALUES
	 ('44c5b357-d2be-4168-ba59-0f94c379c612','QUEM SOMOS','Mais de 20 anos de expertise em Comércio Exterior','Atuamos com excelência em todos os portos, aeroportos e fronteiras do Brasil, garantindo que sua carga chegue ao destino final sem imprevistos e com o melhor custo-benefício.1','Conheça nossa história','Fale conosco','[{"id": "feat-1", "desc": "Taxa de sucesso em processos de Ex-Tarifário", "title": "98% de aprovação no MDIC1"}, {"id": "feat-2", "desc": "Especialistas dedicados para cada cliente", "title": "Atendimento personalizado"}, {"id": "feat-3", "desc": "Processos 100% legais e auditáveis", "title": "Conformidade regulatória total"}]','[{"id": "ach-1", "desc": "Redução de até 100% no II — alíquota 0%", "title": "Ex-Tarifário"}, {"id": "ach-2", "desc": "Para os nossos clientes", "title": "R$ 480M+ economizados"}, {"id": "ach-3", "desc": "Indústria, Agro, Tech, Infraestrutura...", "title": "13+ setores"}, {"id": "ach-4", "desc": "Fundador & Especialista", "title": "Matheus Diniz"}]','2026-05-09 06:41:53.342412','2026-05-09 06:42:12.632124');
INSERT INTO public.air_representation_configs (id,header_badge,header_title_dark,header_title_highlight,import_sections,export_sections,created_at,updated_at,header_description) VALUES
	 ('1580eca3-4ac6-49e1-894f-22bc6d2d4bb7','REPRESENTAÇÃO ESTRATÉGICA','Representações','Aéreas','[{"id": "imp-1", "desc": "Sendo a extensão da sua empresa, atuamos como uma ponte estratégica, assumindo de forma profissional as operações nos aeroportos GRU (Guarulhos) e VCP (Viracopos).", "icon": "Radar", "image": "a6fe1653aacd0a96ae64-exempl1export.jpg", "title": "Representação em Aeroportos", "topics": "Soluções ágeis, seguras e personalizadas\nVasto conhecimento técnico e operacional\nAtendimento exclusivo e dedicado\nParceiro estratégico preparado para complexidade"}, {"id": "imp-2", "desc": "Somos referência no segmento, com atuação ativa desde o período de implantação do CCT Importação.", "icon": "Landmark", "title": "CCT Importação e CE Mercante", "topics": "Rastreabilidade em cada etapa do processo\nFollow-up atualizado em tempo real\nOperações 24 horas por dia, 7 dias por semana\nEquipe pronta para lançamentos em finais de semana e feriados"}, {"id": "imp-3", "desc": "Na Avant, entendemos que a eficiência na distribuição é decisiva para o sucesso das operações de importação.", "icon": "Truck", "title": "Distribuição de Cargas", "topics": "Frota credenciada e parceiros estratégicos\nProcessos padronizados de alta qualidade\nSegurança, agilidade e rastreabilidade total\nRedução de custos e otimização de prazos"}]','[{"id": "exp-1", "desc": "Exportação aérea exige velocidade, precisão e total conformidade. Oferecemos um serviço completo de preparação de cargas para exportações aéreas.", "icon": "Plane", "title": "Preparação de cargas", "topics": "Velocidade e precisão documental\nMáxima segurança e eficiência\nKnow-how em comércio exterior\nRedução de custos operacionais"}, {"id": "exp-2", "desc": "Seu cliente não pode esperar? Cuidamos disso! Oferecemos soluções rápidas, especializadas e seguras em exportação aérea.", "icon": "Zap", "title": "Operações Urgentes", "topics": "Atuação direta nos principais aeroportos\nEstrutura própria e equipe especializada\nProcessos ágeis da coleta ao embarque\nResultados seguros e eficientes"}, {"id": "exp-3", "desc": "A exportação aérea exige precisão documental e total conformidade com os órgãos reguladores.", "icon": "Monitor", "title": "Sistemas comércio exterior", "topics": "Precisão documental e conformidade\nLançamentos no Portal Único\nE-awb especializado\nTerceirização ágil e segura"}, {"id": "exp-4", "desc": "Antes da carga chegar ao aeroporto, cada detalhe da operação faz diferença no sucesso da exportação.", "icon": "PackageCheck", "title": "Transporte e Pré-Embarque", "topics": "Soluções completas de transporte\nCheck-list físico e etiquetagem\nPré-cadastro nos terminais\nAtualizações em tempo real"}]','2026-05-09 18:10:07.047593','2026-05-09 19:18:25.610893','Integramos operações de importação e exportação com foco em agilidade, segurança e conformidade total nos principais aeroportos do Brasil.');
INSERT INTO public.work_steps_configs (id,header_badge,header_title,header_description,cta_text,steps,created_at,updated_at) VALUES
	 ('96b97e2e-41b5-40aa-923d-3d205a97e59b','COMO TRABALHAMOS','Nossa abordagem em 4 etapas','Um fluxo de trabalho transparente e eficiente desenhado para mitigar riscos e maximizar resultados.','Falar com um especialista1','[{"id": "step-1", "desc": "Avaliamos a situação da empresa, os produtos e os objetivos para identificar as melhores oportunidades e regimes aduaneiros aplicáveis.", "title": "Análise e Diagnóstico"}, {"id": "step-2", "desc": "Definimos a estratégia mais adequada para cada operação, com foco em redução de custos, conformidade legal e agilidade no processo.", "title": "Planejamento e Estratégia"}, {"id": "step-3", "desc": "Realizamos todos os procedimentos junto aos órgãos competentes (Receita Federal, MDIC, Siscomex), monitorando cada etapa e respondendo às exigências com agilidade.", "title": "Execução e Acompanhamento"}, {"id": "step-4", "desc": "Entregamos o resultado esperado e mantemos o relacionamento ativo, garantindo que sua empresa esteja sempre em conformidade e aproveitando os benefícios disponíveis.", "title": "Resultado e Continuidade"}]','2026-05-09 06:32:33.201003','2026-05-09 06:32:58.635449');
INSERT INTO public.users (id,"name","password",created_at,updated_at,"role") VALUES
	 ('5596928a-2b72-4ea4-b269-f4d984828bb6','admin','$2b$10$UApsgfEGF9Ah10XHvQYDd.X.QRy/XWBkPHWxIkqHHx5QWO5wjiVlW','2026-05-09 05:30:17.631377','2026-05-09 05:30:17.631377','customer');
INSERT INTO public.testimonials_configs (id,header_badge,header_title,header_description,testimonials,created_at,updated_at) VALUES
	 ('de46832c-2a08-4660-83fe-c5c399b40763','DEPOIMENTOS1','O que nossos clientes dizem','Alguns depoimentos de pessoas e empresas que acreditam em nosso trabalho.1','[{"id": "test-1", "name": "Osvaldo Mendes1", "role": "CEO1", "content": "Atendimento personalizado, rápido, eficiente e proativo. Experiência positiva, recomendamos."}, {"id": "test-2", "name": "Hewerton Precioso", "role": "Engenheiro Eletrônico — Especializado em partes e peças", "content": "Grata surpresa com o atendimento e com os resultados do trabalho contratado. Alto nível moral e intelectual, rapidez e precisão nas respostas e disponibilidade para pesquisar dúvidas inerentes da dinâmica da legislação. Gratidão!"}, {"id": "test-3", "name": "Diogo Fazolo", "role": "Mestre em Direito — Especialista em Direito Aduaneiro", "content": "Conheço a empresa já há alguns anos, atendimento excelente, muita competência e conhecimento da legislação aduaneira. Tenho plena confiança em indicar o trabalho do Sr. Matheus Diniz."}, {"id": "test-1778309650100", "name": "6465", "role": "4645", "content": "646"}]','2026-05-09 06:54:21.904862','2026-05-09 06:54:21.904862');
INSERT INTO public.sectors_configs (id,header_badge,header_title,header_description,sectors,created_at,updated_at) VALUES
	 ('e001c70a-e8e0-471c-a0ae-eea738e9f094','SEGMENTOS1','Setores que atendemos','Soluções logísticas integradas e personalizadas para as demandas mais exigentes do mercado global.1','[{"id": "sec-1", "title": "AGENTES DE CARGA", "iconName": "Users"}, {"id": "sec-2", "title": "COMISSÁRIAS", "iconName": "Shield"}, {"id": "sec-3", "title": "CARGAS AÉREAS", "iconName": "Globe"}, {"id": "sec-4", "title": "CARGAS PERIGOSAS", "iconName": "Zap"}, {"id": "sec-5", "title": "CARGAS URGENTES", "iconName": "Clock"}, {"id": "sec-6", "title": "CARGAS DE PROJETO", "iconName": "Box"}, {"id": "sec-7", "title": "IMPORTADORES", "iconName": "Building"}, {"id": "sec-8", "title": "EXPORTADORES", "iconName": "Truck"}, {"id": "sec-9", "title": "GRU AIRPORT", "iconName": "Target"}, {"id": "sec-10", "title": "VIRACOPOS (VCP)", "iconName": "Target"}, {"id": "sec-11", "title": "OPERAÇÕES COMPLEXAS", "iconName": "Hammer"}, {"id": "sec-12", "title": "LOGÍSTICA REVERSA", "iconName": "RefreshCw"}, {"id": "sec-13", "title": "PHARMA", "iconName": "Pill"}]','2026-05-09 06:53:46.45451','2026-05-09 06:53:56.853712');
INSERT INTO public.migrations ("timestamp","name") VALUES
	 (1768074180034,'CreateUserTable1768074180034'),
	 (1768074180035,'CreateMainBannerTable1768074180035'),
	 (1768074180036,'CreateMainServicesTable1768074180036'),
	 (1768074180037,'CreateWorkStepsTable1768074180037'),
	 (1768074180038,'CreateAboutUsTable1768074180038'),
	 (1768074180039,'CreateSectorsTable1768074180039'),
	 (1768074180040,'CreateTestimonialsTable1768074180040'),
	 (1768074180041,'CreateHomeContactTable1768074180041'),
	 (1768074180042,'CreateFooterTable1768074180042'),
	 (1768074180043,'CreateGeneralContactTable1768074180043');
INSERT INTO public.migrations ("timestamp","name") VALUES
	 (1778346979008,'CreateContactMessagesTable1778346979008'),
	 (1778347528287,'AddReadToContactMessages1778347528287'),
	 (1778348907163,'CreateAirRepresentationConfigTable1778348907163');
INSERT INTO public.main_services_configs (id,header_badge,header_title,header_description,services,created_at,updated_at) VALUES
	 ('b03506ce-b4f5-4846-a913-6b5f9715cb5e','O QUE FAZEMOS','Principais Serviços','Oferecemos soluções completas para integrar sua empresa ao mercado internacional com eficiência e segurança.','[{"id": "card-1", "desc": "Soluções completas de Importação e Exportação com foco em agilidade, segurança e conformidade total em GRU e VCP.", "badge": "MAIS POPULAR", "title": "Representação"}, {"id": "card-2", "desc": "Suporte especializado em E-awb e lançamentos no Portal Único, reduzindo burocracia e acelerando processos digitais.", "badge": "", "title": "Sistemas Comex"}, {"id": "card-3", "desc": "Coleta, etiquetagem, pré-cadastro e entrega nos terminais com segurança e agilidade no pré-embarque internacional.", "badge": "", "title": "Transporte & Logística"}]','2026-05-09 06:14:35.267416','2026-05-09 06:21:38.990637');
INSERT INTO public.main_banners (id,hero_badge,hero_title,hero_description,hero_primary_button_text,hero_secondary_button_text,features,services,stats,footer_stats,created_at,updated_at,services_section_title) VALUES
	 ('37e69f6f-5747-4cf1-9024-a0382db7ac19','LOGÍSTICA AÉREA & SERVIÇOS ADUANEIROS3','Seu parceiro estratégico em Aeroportos GRU | VCP3','Soluções ágeis para agentes de carga e comissárias. Controle a informação, controle o resultado e acelere seu desembaraço aduaneiro.','Falar conosco','Quem somos','[{"id": "feat-1", "text": "+20 anos de experiência"}, {"id": "feat-2", "text": "Empresa 100% brasileira"}, {"id": "feat-3", "text": "Guarulhos, SP"}]','[{"id": "serv-1", "desc": "Expertise global em todos os portos e aeroportos.", "title": "Assessoria Aduaneira"}, {"id": "serv-2", "desc": "Otimização de impostos e regimes especiais.", "title": "Consultoria Tributária"}, {"id": "serv-3", "desc": "Conformidade total com a legislação vigente.", "title": "Segurança Jurídica"}, {"id": "serv-4", "desc": "Suporte especializado em cada etapa do processo.", "title": "Equipe Dedicada"}]','[{"id": "stat-1", "label": "CLIENTES ATENDIDOS", "value": "500+"}, {"id": "stat-2", "label": "ANOS DE EXPERIÊNCIA", "value": "20+"}, {"id": "stat-3", "label": "SATISFAÇÃO", "value": "98%"}]','[{"id": "sstat-1", "label": "ANOS DE EXPERIÊNCIA NO MERCADO", "value": "20+"}, {"id": "sstat-2", "label": "CLIENTES ATENDIDOS", "value": "500+"}, {"id": "sstat-3", "label": "TAXA DE RETENÇÃO E FIDELIDADE", "value": "98%"}, {"id": "sstat-4", "label": "SEGURANÇA JURÍDICA", "value": "100%"}]','2026-05-09 06:03:28.954764','2026-05-09 06:06:18.608504','NOSSOS PRINCIPAIS SERVIÇOS');
INSERT INTO public.home_contact_configs (id,header_badge,header_title,header_description,cta_text,cta_subtext,created_at,updated_at,features,"primaryButton","secondaryButton","textLink") VALUES
	 ('5b45591f-a100-4539-b0b8-74688bd09aae','CONTATO','Precisa de assessoria em Comércio Exterior?','Fale agora com um especialista AVANTCARGO. Atendemos empresas de todo o Brasil com agilidade, competência e mais de 20 anos de experiência.',NULL,NULL,'2026-05-09 06:54:50.304831','2026-05-09 06:56:27.871581','[{"id": "feat-1", "text": "Importação e Exportação"}, {"id": "feat-2", "text": "Ex-Tarifários — alíquota pode chegar a 0%"}, {"id": "feat-3", "text": "Drawback e Radar Siscomex"}, {"id": "feat-4", "text": "Gestão Aduaneira completa"}]','{"link": "https://wa.me/5511964503217", "text": "Falar no WhatsApp"}','{"link": "tel:+5511964503217", "text": "(11) 96450-3217"}','{"link": "/contato", "text": "Ou envie uma mensagem"}');
INSERT INTO public.general_contact_configs (id,header_title_dark,header_title_highlight,header_description,form_title,form_description,whatsapp_number,whatsapp_subtitle,whatsapp_url,email,email_subtitle,instagram_user,instagram_subtitle,instagram_url,address,address_cnpj,address_maps_url,hours_mon_fri,hours_sat,hours_sun,faq_badge,faq_title,faqs,created_at,updated_at) VALUES
	 ('34ff4f77-700c-47c0-a6eb-ebf93a0a357b','Fale com a','AVANTCARGO','Tire suas dúvidas, solicite uma análise gratuita de Ex-Tarifário ou entre em contato para iniciar seu processo de comércio exterior.','Enviar mensagem','Preencha o formulário e nossa equipe entrará em contato em até 24 horas úteis.1','(11) 96450-3217','Resposta rápida — seg a sex, 8h-18h','https://wa.me/5511964503217','comercial@avantcargo.com.br','Resposta em até 24h úteis','@avantcargo','Acompanhe nossas novidades','https://instagram.com/avantcargo','R. Tupi Paulista, 71 - Cidade Industrial Satélite
Guarulhos, SP — CEP 07222-070','CNPJ: 22.837.582/0001-05','https://www.google.com/maps?q=R.+Tupi+Paulista,+71+-+Cidade+Industrial+Satélite+de+São+Paulo,+Guarulhos+-+SP,+07222-070,+Brasil&output=embed','8h às 18h','Fechado','Fechado','FAQ','Perguntas Frequentes','[{"a": "O Ex-Tarifário é um regime que permite a redução temporária da alíquota do Imposto de Importação de bens de capital (BK) e de informática e telecomunicação (BIT), quando não houver produção nacional equivalente.1", "q": "O que é o Ex-Tarifário e como funciona?1", "id": "faq-1"}, {"a": "O prazo médio pode variar entre 60 a 120 dias, dependendo da complexidade do pleito e da agilidade dos órgãos anuentes na análise da inexistência de produção nacional.", "q": "Qual o prazo para aprovação de um Ex-Tarifário?", "id": "faq-2"}, {"a": "Sim, realizamos uma análise preliminar sem custos para identificar a viabilidade do seu pleito e as potenciais economias para sua operação.", "q": "A consulta inicial é gratuita?", "id": "faq-3"}, {"a": "Sim, atendemos empresas em todo o território nacional, com expertise em todos os principais portos, aeroportos e pontos de fronteira do Brasil.", "q": "A AVANTCARGO atende empresas fora de Curitiba?", "id": "faq-4"}, {"a": "Os principais documentos incluem catálogo técnico detalhado, faturas proforma, e especificações que comprovem a tecnologia e a finalidade do bem a ser importado.", "q": "Quais são os principais documentos necessários?", "id": "faq-5"}]','2026-05-09 17:03:22.427548','2026-05-09 17:13:35.865561');
INSERT INTO public.contact_messages (id,"name",company,email,phone,service,message,created_at,updated_at,"read") VALUES
	 ('bdb69c6a-0c41-47a8-a7bb-41542b6d8bb7','ROBSON FEITOSA PIMENTEL','ArtemSite','robson.frontend@gmail.com','41995560628','import','sdfafa','2026-05-09 17:29:33.649374','2026-05-09 17:29:33.649374',false);

INSERT INTO public.footer_configs (id,description,social_links,contact_info,footer_links,copyright_text,terms_link,privacy_link,created_at,updated_at) VALUES
	 ('6f09b5b0-54b1-4150-8a91-dcc146699d84','AvantCargo - Logística e Serviços Aduaneiros. Referência em assessoria de comércio exterior, oferecendo soluções estratégicas e operacionais.','[{"icon": "Linkedin", "link": "https://linkedin.com/company/avantcargo"}, {"icon": "Instagram", "link": "https://instagram.com/avantcargo"}, {"icon": "Facebook", "link": "https://facebook.com/avantcargo"}, {"icon": "Twitter", "link": ""}]','{"email": "comercial@avantcargo.com.br", "phone": "(11) 96450-3217", "address": "Endereço: R. Tupi Paulista, 71 - Cidade Industrial Satélite de São Paulo, Guarulhos - SP, 07222-070, Brasil"}',NULL,'© 2026 AvantCargo - Logística e Serviços Aduaneiros. Todos os direitos reservados.','/termos','/privacidade','2026-05-10 07:26:30.645728','2026-05-10 07:43:24.882404');
