server {
    listen 80;
    server_name _;

    # Frontend (Next.js)
    location / {
        # O Nginx procura pelo 'container_name' na porta que o Next subiu
        proxy_pass http://web-avantcargo:3333; 
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Backend (NestJS)
    location /api {
        # Mudamos de 'api' para 'api-avantcargo'
        proxy_pass http://api-avantcargo:3333;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Como você usa NestJS, se suas rotas NÃO tiverem prefixo /api no código,
        # você PRECISA desta linha abaixo para o Nginx limpar o prefixo:
        # rewrite ^/api/(.*)$ /$1 break;
    }
}